### PR TITLE
Initial Open Source Release - 0.33.0

### PR DESCRIPTION
**Pull request by kenisteward**

### CODE REVIEW

**Comment by kusid** [comment]
yay! congratulations!!

**Comment by kenisteward** [comment]
Thanks :) technically you can review this 📦

**Comment by seoj** [comment]
This is awesome. I'm in tears :'(  I wonder how much of my original code survived. :D

**Comment by saisumughis** [comment]
Awesome!

**Comment by kenisteward** [comment]
@seoj Hey Max!  I've heard good things about you!  I came in after you (I think by a couple months).  I came in as the main UI developer since my background is heavily in UI.  

We upgraded to the newest angular https://angular.io middle of last year.  Unfortunately, that called for a big rewrite but we kept the basic idea of the architecture in tact 👍  Soon we will hopefully have a workflow for taking contributions so you can join back in on the fun :))))

**Pull request merged**
